power: smb5-lib: Mark chg variable as unused in default_irq_handler()
- This fixes following compilation error:
    ../drivers/power/supply/qcom/smb5-lib.c:5542:22: error: unused variable 'chg' [-Werror,-Wunused-variable]
            struct smb_charger *chg = irq_data->parent_data;
                                ^
    1 error generated.

Change-Id: Idc42a1070f9c16688650e3ab77f56d763c6b4c7d
Signed-off-by: hridaya <hridaya@pixelos.net>