drivers: usb: f_fs: Drop unused `ffs` variable
../drivers/usb/gadget/function/f_fs.c:945:19: error: unused variable 'ffs' [-Werror,-Wunused-variable]
        struct ffs_data *ffs = epfile->ffs;
                         ^
1 error generated.

Missed in commit [1].

[1]: 62e9faba65f08ee79d5c9c57b5c450965a46429f {"usb: gadget: f_fs: Remove unused variables"}

Change-Id: Ica547faf0153d0d41056794db2de2041579a4dca
Signed-off-by: hridaya <info.hridayaprajapati@gmail.com>