Revert "drivers/platform: ipa_v3: Don't create debugfs init when !CONFIG_DEBUG_FS"
- The function ipahal_debugfs_init() already is no-op because of !CONFIG_DEBUG_FS, so having this commit is not meaningful.
- This also fixes following compilation error:

../drivers/platform/msm/ipa/ipa_v3/ipahal/ipahal.c:1276:13: error: unused function 'ipahal_debugfs_init' [-Werror,-Wunused-function]
static void ipahal_debugfs_init(void) {}
            ^
1 error generated.

This reverts commit 9e1bdf07db0a00065d160f4f447e839282978d26.