drivers/staging: qcacmn: Fix build when ATH_PROCFS_DIAG_SUPPORT is disabled
Technically, only hif_main.h is required in this instance, but this convention makes things look neater.

This corrects the following compilation errors:

../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/hif/src/ath_procfs.c:248:5: error: no previous prototype for function 'athdiag_procfs_init' [-Werror,-Wmissing-prototypes]
int athdiag_procfs_init(void *scn)
    ^

../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/hif/src/ath_procfs.c:252:6: error: no previous prototype for function 'athdiag_procfs_remove' [-Werror,-Wmissing-prototypes]
void athdiag_procfs_remove(void) {}
     ^

Change-Id: Ide241f5de779d956cd137f3bcccea54c8d2dee04
Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>
Signed-off-by: hridaya <hridaya@pixelos.net>